use LEGO;

CREATE TABLE Part_Categories(
   id   INTEGER  NOT NULL PRIMARY KEY 
  ,name VARCHAR(44) NOT NULL
);
INSERT INTO Part_Categories(id,name) VALUES (1,'Baseplates');
INSERT INTO Part_Categories(id,name) VALUES (2,'Bricks Printed');
INSERT INTO Part_Categories(id,name) VALUES (3,'Bricks Sloped');
INSERT INTO Part_Categories(id,name) VALUES (4,'Duplo, Quatro and Primo');
INSERT INTO Part_Categories(id,name) VALUES (5,'Bricks Special');
INSERT INTO Part_Categories(id,name) VALUES (6,'Bricks Wedged');
INSERT INTO Part_Categories(id,name) VALUES (7,'Containers');
INSERT INTO Part_Categories(id,name) VALUES (8,'Technic Bricks');
INSERT INTO Part_Categories(id,name) VALUES (9,'Plates Special');
INSERT INTO Part_Categories(id,name) VALUES (10,'Tiles Printed');
INSERT INTO Part_Categories(id,name) VALUES (11,'Bricks');
INSERT INTO Part_Categories(id,name) VALUES (12,'Technic Connectors');
INSERT INTO Part_Categories(id,name) VALUES (13,'Minifigs');
INSERT INTO Part_Categories(id,name) VALUES (14,'Plates');
INSERT INTO Part_Categories(id,name) VALUES (15,'Tiles Special');
INSERT INTO Part_Categories(id,name) VALUES (16,'Windows and Doors');
INSERT INTO Part_Categories(id,name) VALUES (17,'Non-LEGO');
INSERT INTO Part_Categories(id,name) VALUES (18,'Hinges, Arms and Turntables');
INSERT INTO Part_Categories(id,name) VALUES (19,'Tiles');
INSERT INTO Part_Categories(id,name) VALUES (20,'Bricks Round and Cones');
INSERT INTO Part_Categories(id,name) VALUES (21,'Plates Round and Dishes');
INSERT INTO Part_Categories(id,name) VALUES (22,'Pneumatics');
INSERT INTO Part_Categories(id,name) VALUES (23,'Panels');
INSERT INTO Part_Categories(id,name) VALUES (24,'Other');
INSERT INTO Part_Categories(id,name) VALUES (25,'Technic Steering, Suspension and Engine');
INSERT INTO Part_Categories(id,name) VALUES (26,'Technic Special');
INSERT INTO Part_Categories(id,name) VALUES (27,'Minifig Accessories');
INSERT INTO Part_Categories(id,name) VALUES (28,'Plants and Animals');
INSERT INTO Part_Categories(id,name) VALUES (29,'Wheels and Tyres');
INSERT INTO Part_Categories(id,name) VALUES (30,'Tubes and Hoses');
INSERT INTO Part_Categories(id,name) VALUES (31,'String, Bands and Reels');
INSERT INTO Part_Categories(id,name) VALUES (32,'Bars, Ladders and Fences');
INSERT INTO Part_Categories(id,name) VALUES (33,'Rock');
INSERT INTO Part_Categories(id,name) VALUES (34,'Supports, Girders and Cranes');
INSERT INTO Part_Categories(id,name) VALUES (35,'Transportation - Sea and Air');
INSERT INTO Part_Categories(id,name) VALUES (36,'Transportation - Land');
INSERT INTO Part_Categories(id,name) VALUES (37,'Bricks Curved');
INSERT INTO Part_Categories(id,name) VALUES (38,'Flags, Signs, Plastics and Cloth');
INSERT INTO Part_Categories(id,name) VALUES (39,'Magnets and Holders');
INSERT INTO Part_Categories(id,name) VALUES (40,'Technic Panels');
INSERT INTO Part_Categories(id,name) VALUES (41,'Bionicle, Hero Factory and Constraction');
INSERT INTO Part_Categories(id,name) VALUES (42,'Belville, Scala and Fabuland');
INSERT INTO Part_Categories(id,name) VALUES (43,'Znap');
INSERT INTO Part_Categories(id,name) VALUES (44,'Mechanical');
INSERT INTO Part_Categories(id,name) VALUES (45,'Power Functions, Mindstorms and Electric');
INSERT INTO Part_Categories(id,name) VALUES (46,'Technic Axles');
INSERT INTO Part_Categories(id,name) VALUES (47,'Windscreens and Fuselage');
INSERT INTO Part_Categories(id,name) VALUES (48,'Clikits');
INSERT INTO Part_Categories(id,name) VALUES (49,'Plates Angled');
INSERT INTO Part_Categories(id,name) VALUES (50,'HO Scale');
INSERT INTO Part_Categories(id,name) VALUES (51,'Technic Beams');
INSERT INTO Part_Categories(id,name) VALUES (52,'Technic Gears');
INSERT INTO Part_Categories(id,name) VALUES (53,'Technic Pins');
INSERT INTO Part_Categories(id,name) VALUES (54,'Technic Bushes');
INSERT INTO Part_Categories(id,name) VALUES (55,'Technic Beams Special');
INSERT INTO Part_Categories(id,name) VALUES (56,'Tools');
INSERT INTO Part_Categories(id,name) VALUES (57,'Non-Buildable Figures (Duplo, Fabuland, etc)');
